import SeatWrapper from './SeatWrapper'
import Seats from './Seats'

const SelectSeat = () => {
  return (
    <SeatWrapper>
      {dummyArr.map((seat) => seat.map((item, idx) => <Seats key={idx} />))}
    </SeatWrapper>
  )
}

export default SelectSeat

const dummyArr = [
  [
    null,
    null,
    { id: 'A-3', status: true },
    { id: 'A-4', status: true },
    { id: 'A-5', status: true },
    ,
    null,
    { id: 'A-7', status: true },
    { id: 'A-8', status: true },
    { id: 'A-9', status: true },
    { id: 'A-10', status: true },
    { id: 'A-11', status: true },
    { id: 'A-12', status: true },
    null,
    null,
  ],
  [
    null,
    null,
    { id: 'A-3', status: true },
    { id: 'A-4', status: true },
    { id: 'A-5', status: true },
    ,
    null,
    { id: 'A-7', status: true },
    { id: 'A-8', status: true },
    { id: 'A-9', status: true },
    { id: 'A-10', status: true },
    { id: 'A-11', status: true },
    { id: 'A-12', status: true },
    null,
    null,
  ],
  [
    null,
    null,
    { id: 'A-3', status: true },
    { id: 'A-4', status: true },
    { id: 'A-5', status: true },
    ,
    null,
    { id: 'A-7', status: true },
    { id: 'A-8', status: true },
    { id: 'A-9', status: true },
    { id: 'A-10', status: true },
    { id: 'A-11', status: true },
    { id: 'A-12', status: true },
    null,
    null,
  ],
  [
    null,
    null,
    { id: 'A-3', status: true },
    { id: 'A-4', status: true },
    { id: 'A-5', status: true },
    ,
    null,
    { id: 'A-7', status: true },
    { id: 'A-8', status: true },
    { id: 'A-9', status: true },
    { id: 'A-10', status: true },
    { id: 'A-11', status: true },
    { id: 'A-12', status: true },
    null,
    null,
  ],
  [
    null,
    null,
    { id: 'A-3', status: true },
    { id: 'A-4', status: true },
    { id: 'A-5', status: true },
    ,
    null,
    { id: 'A-7', status: true },
    { id: 'A-8', status: true },
    { id: 'A-9', status: true },
    { id: 'A-10', status: true },
    { id: 'A-11', status: true },
    { id: 'A-12', status: true },
    null,
    null,
  ],
  [
    null,
    null,
    { id: 'A-3', status: true },
    { id: 'A-4', status: true },
    { id: 'A-5', status: true },
    ,
    null,
    { id: 'A-7', status: true },
    { id: 'A-8', status: true },
    { id: 'A-9', status: true },
    { id: 'A-10', status: true },
    { id: 'A-11', status: true },
    { id: 'A-12', status: true },
    null,
    null,
  ],
  [
    null,
    null,
    { id: 'A-3', status: true },
    { id: 'A-4', status: true },
    { id: 'A-5', status: true },
    ,
    null,
    { id: 'A-7', status: true },
    { id: 'A-8', status: true },
    { id: 'A-9', status: true },
    { id: 'A-10', status: true },
    { id: 'A-11', status: true },
    { id: 'A-12', status: true },
    null,
    null,
  ],
  [
    null,
    null,
    { id: 'A-3', status: true },
    { id: 'A-4', status: true },
    { id: 'A-5', status: true },
    ,
    null,
    { id: 'A-7', status: true },
    { id: 'A-8', status: true },
    { id: 'A-9', status: true },
    { id: 'A-10', status: true },
    { id: 'A-11', status: true },
    { id: 'A-12', status: true },
    null,
    null,
  ],
  [
    null,
    null,
    { id: 'A-3', status: true },
    { id: 'A-4', status: true },
    { id: 'A-5', status: true },
    ,
    null,
    { id: 'A-7', status: true },
    { id: 'A-8', status: true },
    { id: 'A-9', status: true },
    { id: 'A-10', status: true },
    { id: 'A-11', status: true },
    { id: 'A-12', status: true },
    null,
    null,
  ],
]
